name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-16.04
    steps:
      - name: Set up Ruby 2.1.10
        run: |
          sudo add-apt-repository -y ppa:brightbox/ruby-ng
          sudo apt-get -y update
          sudo apt-get -y install ruby2.1 ruby2.1-dev ruby-switch
          sudo apt-get -y install ruby-switch
          sudo ruby-switch --list
          sudo ruby-switch --set ruby2.1
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: 3.4
      - uses: actions/checkout@v2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-hbx_documents-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-hbx_documents-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.14.5'
          bundle config path vendor/bundle
          bundle install
      - name: run tests
        run: |
          bundle exec rspec
